### ISSUE TITLE
Mapping twice

### ISSUE THREAD

**Issue by bookcasey** [thinkful-ei17/john-vernon-spotify#2]
We're mapping over a similar array twice. Can we figure out a way to solve this with one `map()`? :-)

https://github.com/thinkful-ei17/john-vernon-spotify/blob/afb5e5adf828b74062feeb69c7e867522f449a11/spotify.js#L44

https://github.com/thinkful-ei17/john-vernon-spotify/blob/afb5e5adf828b74062feeb69c7e867522f449a11/spotify.js#L48

**Comment by Alderr** [comment]
Accidental push for wrong issue. Got that fixed.
